### ISSUE TITLE
Code C++ est il compatible Windows ?

### ISSUE THREAD

**Issue by LeMoussel** [QwantResearch/mermoz#2]
Bonjour,

Le code C++ de mermoz est il compatible pour être compilé sous Windows avec Visual Studio ?
Si non pense tu que cela soit réalisable de rendre ce code compatible ?

Concernant les dépendances elles sont toutes compatibles Windows (tout du moins les librairies peuvent être téléchargées) sauf pour `urlfactory` pour laquelle je ne sais pas si compatible Win.

+++

Christian.

**Comment by dkurzaj** [comment]
Bonjour,

Nous n'avons jamais testé de le compiler sur Windows, cependant si les dépendances sont en effet disponibles pour Windows, il ne devrait pas y avoir de problème. De plus, `urlfactory` ne dépend que de la bibliothèque standard et est déjà présent dans mermoz sous forme de fork de https://github.com/QwantResearch/urlfactory. Ça ne devrait donc pas poser de soucis.
Nous ne comptons pas pour l'instant ajouter de support Windows à mermoz, mais si pour vos besoins vous y parvenez, nous serons ravis d'accueillir vos contributions afin de permettre cette compatibilité.

Bonne journée ! :)

Dorian
